name = "template-beta-web"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

# OpenNext用の設定
main = ".open-next/server-function/index.mjs"

[env.development]
name = "template-beta-web-dev"

[env.production]
name = "template-beta-web-prod"

# 環境変数の設定（実際の値はwrangler secretで設定）
[vars]
BACKEND_MODE = "monolith"
NODE_ENV = "production"

# KVストレージ（将来使用）
# [[kv_namespaces]]
# binding = "CACHE"
# id = "your-kv-namespace-id"

# R2ストレージ（将来使用）
# [[r2_buckets]]
# binding = "ASSETS"
# bucket_name = "your-r2-bucket"

# 静的アセット設定
[site]
bucket = ".open-next/assets"